apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gct56ckl8-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gct56ckl8-go 
  name: gct56ckl8-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gct56ckl8-go 
